# auto packing [draft]

# path config
set(NETDATA_INSTALL_PATH "${CMAKE_SOURCE_DIR}/install/netdata") 
set(NETDATA_DEPLOY_PATH "/var/netdata/install/netdata")

set(NETDATA_RELATIVE_BIN_PATH "sbin")
set(NETDATA_RELATIVE_WEB_PATH "share/web")        
set(NETDATA_RELATIVE_CONF_D_PATH "lib/netdata/conf.d")   
set(NETDATA_RELATIVE_CONFIG_PATH "etc/netdata")
set(NETDATA_RELATIVE_CACHE_PATH "var/cache")
set(NETDATA_RELATIVE_LOG_PATH "var/log")
set(NETDATA_RELATIVE_LIB_PATH "var/lib")
set(NETDATA_CONF_FILE "netdata.conf")

# create netdata install path
file(REMOVE_RECURSE ${NETDATA_INSTALL_PATH})
file(MAKE_DIRECTORY ${NETDATA_INSTALL_PATH})

# make directory for netdata
file(MAKE_DIRECTORY ${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CACHE_PATH}/netdata)
file(MAKE_DIRECTORY ${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_LIB_PATH}/netdata)
file(MAKE_DIRECTORY ${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_LOG_PATH})

## executable program
install(TARGETS 
        netdata
        apps.plugin
        netdatacli
        slabinfo.plugin
        cgroup-network 
        perf.plugin  
        RUNTIME  DESTINATION
        "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_BIN_PATH}")

## netdata conf
file(GLOB_RECURSE CONF_D_FILES "${CMAKE_SOURCE_DIR}/*.conf")
foreach(CONF_D_FILE ${CONF_D_FILES})
    install(FILES ${CONF_D_FILE} DESTINATION "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONF_D_PATH}")
endforeach()
set(CONF_D_FILES)

## web resource
install(DIRECTORY ${CMAKE_SOURCE_DIR}/web/gui/dashboard DESTINATION "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_WEB_PATH}")
install(FILES ${CMAKE_SOURCE_DIR}/web/gui/dashboard_info.js DESTINATION "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_WEB_PATH}/dashboard")

## netdata.conf
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "# netdata configuration\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "# global netdata configuration\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "[global]\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    run as user = root\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    hostname = unknown\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    update every = 1\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    config directory = ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    stock config directory = ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_CONF_D_PATH}\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    log directory = ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_LOG_PATH}\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    web files directory = ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_WEB_PATH}/dashboard\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    cache directory = ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_CACHE_PATH}\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    lib directory = ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_LIB_PATH}\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    log directory = ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_LOG_PATH}\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    home directory =  ${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_LIB_PATH}\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    lock directory = ${NETDATA_DEPLOY_PATH}/lock\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    plugins directory = \"${NETDATA_DEPLOY_PATH}/${NETDATA_RELATIVE_BIN_PATH}\"\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "[web]\n")
file(APPEND "${NETDATA_INSTALL_PATH}/${NETDATA_RELATIVE_CONFIG_PATH}/${NETDATA_CONF_FILE}" "    default port = 25000\n")
